function Bmelgren__Pentultimate_Nerual_Slipstream_Tweak_2() {
  with (Math) {
    fRating=3;
    gamma=2;
    decay=0.95;
    echo_zoom=3.007504;
    echo_alpha=0;
    echo_orient=1;
    wave_mode=0;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=0;
    darken_center=1;
    bMotionVectorsOn=0;
    bRedBlueStereo=0;
    mv_x=12;
    mv_y=9;
    brighten=0;
    darken=1;
    solarize=0;
    invert=0;
    wave_a=1;
    fWaveScale=0.880224;
    fWaveSmoothing=0;
    wave_mystery=-0.5;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1.074097;
    fShader=1;
    zoom=1;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.01;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=0;
    ib_size=0.01;
    ib_r=0.25;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0;
    warp = 0;
    wave_r = wave_r + .5*sin(time*333) + bass*.3;
    wave_g = wave_g + .5*sin(time*222) + treb*.3;
    wave_b = wave_b + .5*sin(time*111) + mid*.3;
    rot = .4*sin(mid_att*.05);
    // per_pixel_1=ray = pow(rad,1.8)+.05;
    // per_pixel_2=zoom = (ray/rad)*1.4 + .3*sin(ang*(bass*5))+(bass*.2);
  }
}
register_preset( Bmelgren__Pentultimate_Nerual_Slipstream_Tweak_2);
