function Idiot__Tentacle_Dreams_Remix() {
  with (Math) {
    fRating=2;
    gamma=1;
    decay=0.98;
    echo_zoom=0.999609;
    echo_alpha=0;
    echo_orient=3;
    wave_mode=0;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=1;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1;
    fWaveScale=3.544918;
    fWaveSmoothing=0.63;
    wave_mystery=-0.36;
    fModWaveAlphaStart=0.71;
    fModWaveAlphaEnd=1.3;
    warp_speed=1;
    warp_scale=1.331;
    zoomexp=1.0001;
    fShader=0;
    zoom=1.000376;
    rot=1;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=0.01;
    sx=0.999944;
    sy=0.999904;
    wave_r=1;
    wave_g=1;
    wave_b=1;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.0499;
    ob_r=0.11;
    ob_g=0.5;
    ob_b=1;
    ob_a=0;
    ib_size=0.055;
    ib_r=0;
    ib_g=0;
    ib_b=0;
    ib_a=0;
    mv_x=1.28;
    mv_y=48;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.5;
    mv_r=1;
    mv_g=1;
    mv_b=0;
    mv_a=0;
    vol_att=bass_att+treb_Att+mid_att;
    bass_thresh = above(bass_att,bass_thresh)*2 + (1-above(bass_att,bass_thresh))*((bass_thresh-1.3)*0.96+1.3);
    treb_thresh=above(treb_att,treb_thresh)*2+
    (1-above(treb_att,treb_thresh))*((treb_thresh-1.3)*0.96+1.3);
    mid_thresh=above(mid_att,mid_thresh)*2+
    (1-above(mid_mid_att,mid_thresh))*((mid_thresh-1.3)*0.96+1.3);
    vol_thresh=bass_thresh+treb_thresh+mid_thresh;
    treb_effect=max(max(treb,treb_Att),treb_thresh);
    bass_effect=max(max(Bass,bass_Att),bass_thresh);
    mid_effect=max(max(mid,mid_att),mid_thresh);
    vol_effect=bass_effect+treb_effect+mid_effect;
    react=vol;
    new_bass=if_milk(above(react,bass_effect),bass&bass_att,bass_effect+bass_thresh);
    new_treb=if_milk(above(react,treb_effect),treb&treb_att,treb_Effect+treb_thresh);
    new_mid=if_milk(above(react,mid_effect),mid&mid_Att,mid_effect+mid_thresh);
    new_vol=new_bass+new_treb+new_mid+.04;
    change=bnot(1);
    q1=new_bass;
    q2=new_treb;
    q3=new_mid;
    q4=new_vol;
    q5=bass_thresh;
    q6=treb_thresh;
    q7=mid_thresh;
    q8=vol_thresh;
    wave_r=.4+.3*Sin(time+Q1);
    wave_b=.3+.6*sin(time+q2);
    wave_g=.5+.5*sin(time-q1);
    
    
    // per_pixel_1=rot_effect=.3*Sin(rad-+ang*x+yQ3)*rad*sin(if_milk(Above(Q1,q2),q5,-q5))*rad-.1*sin(Q3*rad+ang-x*y*rad*q1);
    // per_pixel_2=rot_effect2=if_milk(Above(q5,q6),rot_effect,-rot_effect)-rad*.25*sin(Q6)+.2*Sin(Q6)-x*.25-.01*sin(Q7)-
    // per_pixel_3=above(rad,x)*sin(Q8)*.25*sin(time*.65);
    // per_pixel_4=rot=if_milk(above(q5,q7),rot_effect,rot_effect2);
    // per_pixel_5=cx_x=if_milk(Above(Q2,q3),cx+.5*Sin(x-.3*Rad*cos(q1-.3)-.2-rad*sin(q6)),.5);
    // per_pixel_6=cy_x=if_milk(Above(Q2,q3),cy+.5*sin(y-.3*rad*cos(q2-.3)-.2-rad*sin(q5)),.5);
    // per_pixel_7=cx=if_milk(above(q5,q6),cx_x,cx_x-.2);
    // per_pixel_8=cy=if_milk(Above(Q5,q7),cy_x,cy_x-.2);
    // per_pixel_9=zoom=zoom-.10*rad*sin(Q1)*Rad-.02*sin(q6-x+y*sin(q6+rad)+rad);
    // per_pixel_10=//388-0250;
  }
}
register_preset( Idiot__Tentacle_Dreams_Remix);
