function Krash__Digital_Flame() {
  with (Math) {
    fRating=3;
    gamma=2;
    decay=0.9;
    echo_zoom=1;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=6;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=0;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1;
    fWaveScale=0.3697;
    fWaveSmoothing=0.75;
    wave_mystery=0;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=53.523884;
    warp_scale=0.408391;
    zoomexp=1;
    fShader=0;
    zoom=1;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.6999;
    wave_g=0.6;
    wave_b=0.8;
    wave_x=0;
    wave_y=0.5;
    ob_size=0;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=0;
    ib_size=0;
    ib_r=0;
    ib_g=0;
    ib_b=0;
    ib_a=0;
    mv_x=12;
    mv_y=9;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    q1 = (bass_att + mid_att + treb_att) /3;
    q2 = time + 1000;
    bass_thresh = above(bass_att,bass_thresh)*2 + (1-above(bass_att,bass_thresh))*((bass_thresh-1.4)*0.95+1.4);
    treb_thresh = above(treb_att,treb_thresh)*2 + (1-above(treb_att,treb_thresh))*((treb_thresh-1.5)*0.85+1.2);
    bass_on = above(bass_thresh,1.9);
    treb_on = above(treb_thresh,1.9);
    swapcolour = bass_on - treb_on;
    red_aim = if_milk(equal(swapcolour,1),1,if_milk(equal(swapcolour,0),0.9,0.7));
    green_aim = if_milk(equal(swapcolour,1),0.7,if_milk(equal(swapcolour,0),0.3,0.6));
    blue_aim = if_milk(equal(swapcolour,1),0,if_milk(equal(swapcolour,0),0.2,0.8));
    red = red + (red_aim - red)*0.5;
    green = green + (green_aim - green)*0.5;
    blue = blue + (blue_aim - blue)*0.5;
    wave_r = red;
    wave_g = green;
    wave_b = blue;
    // per_pixel_1=dy = -0.1*(q1-1)*log(2-(abs(y*2 - 1.8)));
    // per_pixel_2=dy = below(dy,0.02)*dy - 0.02;
    // per_pixel_3=dy = dy + 0.01*(sin((x*q2*0.483) + (y*q2*1.238)) + sin((x*q2*1.612) + (y*q2*0.648)));
  }
}
register_preset( Krash__Digital_Flame);
