function Krash__systolic_pressure() {
  with (Math) {
    fRating=3;
    gamma=2;
    decay=1;
    echo_zoom=1;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=0;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=1;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1;
    fWaveScale=0.071719;
    fWaveSmoothing=0.75;
    wave_mystery=-0.16;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=9.8608;
    warp_scale=16.2174;
    zoomexp=1.503744;
    fShader=0;
    zoom=1;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=0.999999;
    sx=1;
    sy=1;
    wave_r=0.9;
    wave_g=0.2;
    wave_b=0.4;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.5;
    ob_r=0.05;
    ob_g=0;
    ob_b=0;
    ob_a=0.02;
    ib_size=0.5;
    ib_r=0.05;
    ib_g=0;
    ib_b=0;
    ib_a=0.02;
    mv_x=64;
    mv_y=48;
    mv_l=5;
    mv_r=0;
    mv_g=0;
    mv_b=0;
    mv_a=0;
    warp = 0;
    volume = 0.3*(bass+mid+att);
    xamptarg = if_milk(equal(frame%15,0),min(0.25*volume*bass_att,0.5),xamptarg);
    xamp = xamp + 0.5*(xamptarg-xamp);
    xdir = if_milk(above(abs(xpos),xamp),-sign(xpos),if_milk(below(abs(xspeed),0.1),2*above(xpos,0)-1,xdir));
    xspeed = xspeed + xdir*xamp - xpos - xspeed*0.055*below(abs(xpos),xamp);
    xpos = xpos + 0.001*xspeed;
    yamptarg = if_milk(equal(frame%15,0),min(0.15*volume*treb_att,0.5),yamptarg);
    yamp = yamp + 0.5*(yamptarg-yamp);
    ydir = if_milk(above(abs(ypos),yamp),-sign(ypos),if_milk(below(abs(yspeed),0.1),2*above(ypos,0)-1,ydir));
    yspeed = yspeed + ydir*yamp - ypos - yspeed*0.055*below(abs(ypos),yamp);
    ypos = ypos + 0.001*yspeed;
    beatrate = equal(beatrate,0) + (1-equal(beatrate,0))*(below(volume,0.01) + (1-below(volume,0.01))*beatrate);
    lastbeat = lastbeat + equal(lastbeat,0)*time;
    meanbass_att = 0.1*(meanbass_att*9 + bass_att);
    peakbass_att = max(bass_att,peakbass_att);
    beat = above(volume,0.8)*below(peakbass_att - bass_att, 0.05*peakbass_att)*above(time - lastbeat, 0.1 + 0.5*(beatrate - 0.1));
    beatrate = max(if_milk(beat,if_milk(below(time-lastbeat,2*beatrate),0.1*(beatrate*9 + time - lastbeat),beatrate),beatrate),0.1);
    peakbass_att = beat*bass_att + (1-beat)*peakbass_att*(above(time - lastbeat, 2*beatrate)*0.95 + (1-above(time - lastbeat, 2*beatrate))*0.995);
    lastbeat = beat*time + (1-beat)*lastbeat;
    peakbass_att = max(peakbass_att,1.1*meanbass_att);
    wave_x = xpos + 0.5;
    wave_y = ypos + 0.5;
    wave_r = wave_r + 0.250*( 0.60*sin(0.980*time) + 0.40*sin(1.047*time) );
    wave_g = wave_g + 0.150*( 0.60*sin(0.835*time) + 0.40*sin(1.081*time) );
    wave_b = wave_b + 0.150*( 0.60*sin(0.814*time) + 0.40*sin(1.011*time) );
    wave_mystery = -0.17 + 0.03*(0.6*sin(0.637*time) + 0.4*sin(0.949*time));
    mv_r = if_milk(beat, 1, ib_r);
    mv_b = if_milk(beat, wave_b, ib_b);
    mv_a = if_milk(beat, 0.1, ib_a);
    ib_a = 0.015;
    q3 = wave_mystery;
    q1 = wave_x;
    q2 = 1- wave_y;
    // per_pixel_1=newx = x - q1;
    // per_pixel_2=newy = y - q2;
    // per_pixel_3=newrad = sqrt((newx)*(newx)+0.5625*(newy)*(newy))*2;
    // per_pixel_4=newzoom = pow(1.05 + below(newrad,0.39+q3)*(0.6-newrad), pow(1 + 0.5*cos(newrad+2*q3+0.28), newrad*2-1));
    // per_pixel_5=dx = -0.0005 + (newx)*newzoom - newx;
    // per_pixel_6=dy = -0.0005 + (newy)*newzoom - newy;
  }
}
register_preset( Krash__systolic_pressure);
