function Krash_and_Idiot__Memories_Of_The_Castle() {
  with (Math) {
    fRating=3;
    gamma=1;
    decay=0.99;
    echo_zoom=0.999609;
    echo_alpha=0;
    echo_orient=3;
    wave_mode=1;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=1;
    darken_center=1;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1;
    fWaveScale=0.357394;
    fWaveSmoothing=0.63;
    wave_mystery=-0.6;
    fModWaveAlphaStart=0.71;
    fModWaveAlphaEnd=1.3;
    warp_speed=1;
    warp_scale=1.331;
    zoomexp=1.0001;
    fShader=0;
    zoom=1.000376;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=0.01;
    sx=0.9999;
    sy=0.999904;
    wave_r=0;
    wave_g=0;
    wave_b=0.2;
    wave_x=0.5;
    wave_y=0.49;
    ob_size=0.0499;
    ob_r=0.11;
    ob_g=0.5;
    ob_b=1;
    ob_a=0;
    ib_size=0.055;
    ib_r=0;
    ib_g=0;
    ib_b=0;
    ib_a=0;
    mv_x=12;
    mv_y=9;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    vol_att=bass_att+treb_Att+mid_att;
    bass_thresh = above(bass_att,bass_thresh)*2 + (1-above(bass_att,bass_thresh))*((bass_thresh-1.3)*0.96+1.3);
    treb_thresh=above(treb_att,treb_thresh)*2+
    (1-above(treb_att,treb_thresh))*((treb_thresh-1.3)*0.96+1.3);
    mid_thresh=above(mid_att,mid_thresh)*2+
    (1-above(mid_mid_att,mid_thresh))*((mid_thresh-1.3)*0.96+1.3);
    vol_thresh=bass_thresh+treb_thresh+mid_thresh;
    react=vol;
    new_bass=if_milk(above(react,bass_effect),bass&bass_att,bass_effect+bass_thresh);
    new_treb=if_milk(above(react,treb_effect),treb&treb_att,treb_Effect+treb_thresh);
    new_mid=if_milk(above(react,mid_effect),mid&mid_Att,mid_effect+mid_thresh);
    new_vol=new_bass+new_treb+new_mid+.04;
    rotadd = rotadd+sign(0.6*sin(time*0.456) + 0.4*sin(time*0.965));
    q1=new_bass;
    q2=new_treb;
    q3=0.03*rotadd;
    q4=new_vol;
    q5=bass_thresh;
    q6=treb_thresh;
    q7=mid_thresh;
    q8=vol_thresh;
    mode = frame%2;
    wave_r=.3+.5*sin(new_mid-time)+mode;
    wave_g=.5-.2*sin(q2-time)-mode;
    wave_b=.2+.6*sin(q1-time)-mode;
    wave_mode = if_milk(mode,0,wave_mode);
    // per_pixel_1=shine=band(rad,2)-rad%8*rad%2+.2*sin(q1)+.1*sin(above(Q1,q2));
    // per_pixel_2=zoom=shine+.2*sin(above(q2,q1)-rad*sin(q5&time*.75*sin(above(Q5,q6))));
    // per_pixel_3=zoom = zoom - below(rad,0.5)*0.8*(zoom-1);
    // per_pixel_4=rot=if_milk(above(q1,q2),.2*sin(q1),-.2*sin(q2))+above(rad,0.5)*q3;
  }
}
register_preset( Krash_and_Idiot__Memories_Of_The_Castle);
