function Krash_and_Zylot__Inside_The_Planar_Portal_Indecision_Mix() {
  with (Math) {
    fRating=3;
    gamma=2;
    decay=0.98;
    echo_zoom=2;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=0;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=1;
    darken_center=1;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=0.8;
    fWaveScale=0.224799;
    fWaveSmoothing=0.75;
    wave_mystery=-0.44;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1;
    fShader=0;
    zoom=1;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.01;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=1;
    ib_size=0.01;
    ib_r=0.25;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0;
    mv_x=0;
    mv_y=0;
    mv_dx=0;
    mv_dy=0;
    mv_l=5;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=1;
    warp = 0;
    wave_mystery = wave_mystery + bass*.06;
    wave_r = bass*.4;
    wave_g = treb*.4;
    wave_b = mid*.4;
    q1 = bass*0.03;
    q2 = treb*0.03;
    vol = 0.167*(bass+mid);
    xamptarg = if_milk(equal(frame%15,0),min(0.5*vol*bass_att,0.5),xamptarg);
    xamp = xamp + 0.5*(xamptarg-xamp);
    xdir = if_milk(above(abs(xpos),xamp),-sign(xpos),if_milk(below(abs(xspeed),0.1),2*above(xpos,0)-1,xdir));
    xspeed = xspeed + xdir*xamp - xpos - xspeed*0.055*below(abs(xpos),xamp);
    xpos = xpos + 0.001*xspeed;
    wave_x = 0.5+xpos;
    q3 = wave_x;
    q4 = 1-wave_y;
    q5 = 0.5+0.3*xpos;
    // per_pixel_1=newx = x - q3;
    // per_pixel_2=newy = y - q4;
    // per_pixel_3=inbox = above(x,q3-0.1-q2)*below(x,q3+0.1+q2)*above(y,q4-0.1-q1)*below(y,q4+0.1+q1);
    // per_pixel_4=newzoom = if_milk(inbox,1.04,q5);
    // per_pixel_5=dx = (newx)*newzoom - newx + (1-inbox)*q5;
    // per_pixel_6=dy = (newy)*newzoom - newy + (1-inbox);
  }
}
register_preset( Krash_and_Zylot__Inside_The_Planar_Portal_Indecision_Mix);
