function Krash__Chronoshift() {
  with (Math) {
    fRating=3;
    gamma=2;
    decay=0.97;
    echo_zoom=1;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=0;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=0;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1;
    fWaveScale=0.741922;
    fWaveSmoothing=0.75;
    wave_mystery=-0.5;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=0.248317;
    fShader=0;
    zoom=1;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=0;
    ib_size=0;
    ib_r=0;
    ib_g=0;
    ib_b=0;
    ib_a=0;
    mv_x=12;
    mv_y=9;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    warp=0;
    wave_r = wave_r + 0.350*( 0.60*sin(0.823*time) + 0.40*sin(0.916*time) );
    wave_g = wave_g + 0.350*( 0.60*sin(0.900*time) + 0.40*sin(1.023*time) );
    wave_b = wave_b + 0.350*( 0.60*sin(0.808*time) + 0.40*sin(0.949*time) );
    bass_time = bass_time + if_milk(above(treb_att,1.2),2*treb_att,1)*(time-last_time);
    q1 = bass_time;
    last_time = time;
    bass_thresh = above(bass_att,bass_thresh)*2 + (1-above(bass_att,bass_thresh))*((bass_thresh-1.3)*0.99+1.3);
    minute_dir = if_milk(equal(minute_dir,0),-1,if_milk(equal(bass_thresh,2),sign(sin(time)),minute_dir));
    hour_dir = if_milk(equal(hour_dir,0),-1,if_milk(equal(bass_thresh,2),sign(cos(time)),hour_dir));
    q2 = minute_dir;
    q3 = hour_dir;
    // per_pixel_1=angval = 0.3/sqrt((3.14*tan(q2*ang*0.5-q1))+4);
    // per_pixel_2=angval2 = 0.3/sqrt((3.14*tan(q3*ang*0.5-q1/12+1.2))+4);
    // per_pixel_3=zoom = 0.8+3*sqr(angval);
    // per_pixel_4=zoom = zoom + if_milk(below(rad,0.4),3*sqr(angval2),0);
    // per_pixel_5=rot = 0.1*(sin(angval)-sin(angval2));
  }
}
register_preset( Krash__Chronoshift);
