function Mstress_and_Zylot__Acid_UFO() {
  with (Math) {
    fRating=3;
    gamma=1.980001;
    decay=0.99;
    echo_zoom=2;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=5;
    wave_additive=0;
    wave_usedots=1;
    bWaveThick=1;
    bModWaveAlphaByVolume=1;
    wave_brighten=0;
    wrap=1;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=1;
    solarize=0;
    invert=0;
    wave_a=1.179297;
    fWaveScale=0.491915;
    fWaveSmoothing=0.216;
    wave_mystery=-0.42;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=2.853;
    zoomexp=1;
    fShader=0;
    zoom=1.001829;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=0.01;
    sx=0.999005;
    sy=0.999005;
    wave_r=0.77;
    wave_g=0.6;
    wave_b=0.6;
    wave_x=0.42;
    wave_y=0.5;
    ob_size=0.02;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=0.250001;
    ib_size=0.155;
    ib_r=0.25;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0.27;
    mv_x=30.079998;
    mv_y=0;
    mv_dx=0.32;
    mv_dy=0.42;
    mv_l=3.199998;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    warp = 0;
    wave_r = min(1,max(0,0.3*bass));
    wave_g = min(1,max(0,0.3*mid));
    wave_b = min(1,max(0,0.3*treb));
    
    //Thanks to Zylot for rainbow generator
    counter1 = if_milk(equal(counter2,1),if_milk(equal(counter1,1),0,counter1+.2),1);
    counter2 = if_milk(equal(counter1,1),if_milk(equal(counter2,1),0,counter2+.2),1);
    cdelay1 = if_milk(equal(cdelay2,1),1,if_milk(equal(colorcounter%2,1),if_milk(equal(counter1,1),2 ,0), if_milk(equal(counter2,1),2,0)));
    cdelay2 = if_milk(equal(cdelay1,2),1,0);
    colorcounter = if_milk(above(colorcounter,7),0,if_milk(equal(cdelay1,1),colorcounter+1,colorcounter));
    ob_r = if_milk(equal(colorcounter,1),1, if_milk(equal(colorcounter,2),1, if_milk(equal(colorcounter,3),1, if_milk(equal(colorcounter,4),sin(counter2+2.1), if_milk(equal(colorcounter,5),0, if_milk(equal(colorcounter,6),0,sin(counter1)))))));
    ob_g = if_milk(equal(colorcounter,1),0, if_milk(equal(colorcounter,2),sin(counter2*.5), if_milk(equal(colorcounter,3),sin((counter1+1.75)*.4), if_milk(equal(colorcounter,4),1, if_milk(equal(colorcounter,5),1, if_milk(equal(colorcounter,6),sin(counter2+2),0))))));
    ob_b = if_milk(equal(colorcounter,1),sin(counter1+2.1), if_milk(equal(colorcounter,2),0, if_milk(equal(colorcounter,3),0, if_milk(equal(colorcounter,4),0, if_milk(equal(colorcounter,5),sin(counter1), if_milk(equal(colorcounter,6),1,1))))));
    
    mbass=max(bass_att,3);
    xmovn = 0.1*random_integer(10)*mbass*0.015*(1-2*above(random_integer(10),5));
    ymovn = pow(pow(mbass*0.015,2)-pow(xmovn,2),1/2)*(1-2*above(random_integer(10),5));
    //ymovn=.05;
    xmov = if_milk(beat,xmovn,xmov*.9);
    ymov = if_milk(beat,ymovn,ymov*.9);
    q1=oldx;
    q2=oldy;
    out_x = bor(above(q1+xmov,.9),below(q1+xmov,.1));
    out_y = bor(above(q2+ymov,.9),below(q2+ymov,.1));
    xmov = xmov + (-2*xmov*out_x);
    ymov = ymov + (-2*ymov*out_y);
    wave_x =  q1+xmov ;
    wave_y = q2+ymov;
    q1=wave_x;
    q2=wave_y;
    oldx = q1;
    oldy = q2;
    
    decay = decay - 0.91*(treble);
    
    //Thanks to krash for beat detection (modif_milkied)
    volume = 0.3*bass+mid;
    beatrate = equal(beatrate,0) + (1-equal(beatrate,0))*(below(volume,0.01) + (1-below(volume,0.01))*beatrate);
    lastbeat = lastbeat + equal(lastbeat,0)*time;
    meanbass_att = 0.1*(meanbass_att*9 + bass_att);
    runmeanbass =(runmeanbass*2 + bass_att)/3;
    peakbass_att = max(bass_att,peakbass_att);
    beat = above(volume,0.8)*above(bass_att,runmeanbass*1.1)*below(peakbass_att - bass_att, 0.05*peakbass_att)*above(time - lastbeat, 0.1 + 0.5*(beatrate - 0.1));
    beatrate = max(if_milk(beat,if_milk(below(time-lastbeat,2*beatrate),0.1*(beatrate*9 + time - lastbeat),beatrate),beatrate),0.1);
    peakbass_att = beat*bass_att + (1-beat)*peakbass_att*(above(time - lastbeat, 2*beatrate)*0.95 + (1-above(time - lastbeat, 2*beatrate))*0.995);
    lastbeat = beat*time + (1-beat)*lastbeat;
    peakbass_att = max(peakbass_att,1.1*meanbass_att);
    q3=volume+treb;
    monitor =meanbass_att;
    // per_pixel_1=mx= x-q1;
    // per_pixel_2=my = y-(1-q2);
    // per_pixel_3=mrad = pow(pow(mx,2)+pow(my,2),0.5)*pow(2,0.5);
    // per_pixel_4=cx = q1;
    // per_pixel_5=cy = 1-q2;
    // per_pixel_6=rot= rot + below(mrad-0.18,0)*0.5*sin(mrad*40)*(mrad-0.1)*40- above(mrad-0.18,0)*0.3*sin(mrad*2)*(mrad-0.1)*sin((cx-0.5)*(cy-0.5)*6.28)*q3;
    // per_pixel_7=zoom= zoom - above(mrad-0.18,0)*0.05*mrad*q3;
    // per_pixel_8=dx = dx +below(mrad-0.18,0)*0.015*(mx/mrad);
    // per_pixel_9=dy = dy +below(mrad-0.18,0)*0.015*(my/mrad);
    oldx=.5;
    oldy=.5;
  }
}
register_preset( Mstress_and_Zylot__Acid_UFO);
