function Rovastar_and_Krash__Sweetness_and_Light() {
  with (Math) {
    fRating=2;
    gamma=2;
    decay=1;
    echo_zoom=1;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=0;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=0;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1;
    fWaveScale=0.550447;
    fWaveSmoothing=0.75;
    wave_mystery=-0.2199;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1;
    fShader=0;
    zoom=0.9999;
    rot=0.1;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.01;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=0.13;
    ib_size=0;
    ib_r=0;
    ib_g=0;
    ib_b=0;
    ib_a=0;
    mv_x=64;
    mv_y=48;
    mv_dx=0;
    mv_dy=0;
    mv_l=0;
    mv_r=0;
    mv_g=0.7;
    mv_b=1;
    mv_a=0;
    warp=0;
    wave_r = wave_r + 0.45*(0.5*sin(time*0.701)+ 0.3*cos(time*0.438));
    wave_b = wave_b - 0.4*(0.5*sin(time*4.782)+0.5*cos(time*0.522));
    wave_g = wave_g + 0.4*sin(time*1.731);
    vol = 0.167*(bass+mid+att);
    xamptarg = if_milk(equal(frame%15,0),min(0.5*vol*bass_att,0.5),xamptarg);
    xamp = xamp + 0.5*(xamptarg-xamp);
    xdir = if_milk(above(abs(xpos),xamp),-sign(xpos),if_milk(below(abs(xspeed),0.1),2*above(xpos,0)-1,xdir));
    xspeed = xspeed + xdir*xamp - xpos - xspeed*0.055*below(abs(xpos),xamp);
    xpos = xpos + 0.001*xspeed;
    wave_x = 1.25*xpos + 0.5;
    yamptarg = if_milk(equal(frame%15,0),min(0.3*vol*treb_att,0.5),yamptarg);
    yamp = yamp + 0.5*(yamptarg-yamp);
    ydir = if_milk(above(abs(ypos),yamp),-sign(ypos),if_milk(below(abs(yspeed),0.1),2*above(ypos,0)-1,ydir));
    yspeed = yspeed + ydir*yamp - ypos - yspeed*0.055*below(abs(ypos),yamp);
    ypos = ypos + 0.001*yspeed;
    wave_y = 1.25*ypos + 0.5;
    dx = dx + dx_residual;
    dy = dy + dy_residual;
    bass_thresh = above(bass_att,bass_thresh)*2 + (1-above(bass_att,bass_thresh))*((bass_thresh-1.3)*0.96+1.3);
    dx_residual = equal(bass_thresh,2)*0.003*sin(time*7) + (1-equal(bass_thresh,2))*dx_residual;
    dy_residual = equal(bass_thresh,2)*0.001*sin(time*9) + (1-equal(bass_thresh,2))*dy_residual;
    rot = 0.1;
    q1=xpos +0.25*ypos + 0.5;
    q2=ypos +0.25*xpos + 0.5;
    // per_pixel_1=cx = (0&(x*10-0.5))*0.1+0.05;
    // per_pixel_2=cy = (0&(y*10-0.5))*0.1+0.05;
    // per_pixel_3=newx = q1-x;
    // per_pixel_4=newy = q2-y;
    // per_pixel_5=newrad = sqrt((newx)*(newx)+0.5625*(newy)*(newy))*2;
    // per_pixel_6=newzoom = pow(1.05 + 0.03*newrad, pow(0.01+sin(newrad*newrad), newrad*2-1));
    // per_pixel_7=dx = (newx)*newzoom - newx;
    // per_pixel_8=dy = (newy)*newzoom - newy;
    // per_pixel_9=dx =dx*0.1;
    // per_pixel_10=dy=dy*0.1;
    // per_pixel_11=rot = 2.41*newrad*(0.5*(0.65-rad));
  }
}
register_preset( Rovastar_and_Krash__Sweetness_and_Light);
