function Rozzor_and_Idiot__Any_Other_Deep_Rising() {
  with (Math) {
    fRating=2;
    gamma=1.14;
    decay=0.91;
    echo_zoom=0.591237;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=1;
    wave_additive=1;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=0;
    darken_center=1;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1.008018;
    fWaveScale=1.001829;
    fWaveSmoothing=0;
    wave_mystery=0.5;
    fModWaveAlphaStart=0.71;
    fModWaveAlphaEnd=1.3;
    warp_speed=1;
    warp_scale=1.331;
    zoomexp=1;
    fShader=0;
    zoom=1.001827;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=0.01;
    sx=0.905286;
    sy=0.932718;
    wave_r=0.65;
    wave_g=0.65;
    wave_b=0.65;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0;
    ob_r=0.1;
    ob_g=0.1;
    ob_b=0.1;
    ob_a=0.01;
    ib_size=0.005;
    ib_r=0;
    ib_g=0;
    ib_b=0;
    ib_a=0.5;
    mv_x=11.52;
    mv_y=10.559999;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0.5;
    slowtime = slowtime+beat*time;
    ying = if_milk(below(ying,1),1,ying);
    ying = if_milk (beat,ying + bnot(time*10%3),ying);
    yin = ying%2;
    vol_now =  .4 * bass + 0.1 * (bass_att+treb+mid);
    vol_mean =  if_milk(equal(frame%50,0),vol_mean-0.5*(vol_mean-vol_now),0.1*(vol_mean*9 + vol_now));
    beat = if_milk(above(vol_now,1.5*vol_mean),1,0);
    beatcount = if_milk(bnot(time%5000),0,beatcount);
    beatcount = beatcount +.05*beat;
    yang = bnot(beatcount%2);
    ib_r = 0;
    ib_g = pow(abs(sign(sin(slowtime))),2)*sin(slowtime);
    ib_b= cos(slowtime)*sign(cos(slowtime))*pow(abs(sign(sin(slowtime))),2);
    mv_g = sin(slowtime)*(sign(sin(slowtime))-1)*(sign(sin(slowtime)));
    mv_b = -1*abs(cos(slowtime))+1;
    mv_r = .8;
    redneg = if_milk(below(ib_r,0),1,0);
    greenneg = if_milk(below(ib_g,0),1,0);
    blueneg = if_milk(below(ib_b,0),1,0);
    wave_r = if_milk(redneg,if_milk(bor(greenneg , blueneg),1,1+ib_r),ib_r);
    wave_g = if_milk(greenneg,if_milk(equal(greenneg + blueneg,2),1,1+ib_g),ib_g);
    wave_b = if_milk(blueneg,1 + ib_b, ib_b);
    q1 = if_milk(yin,sin(slowtime),q1);
    q2 = if_milk(yin,cos(slowtime),0);
    q3 = sin(beatcount);
    dx = if_milk(yin,.01*sin(slowtime),if_milk(equal(yin,yang),0,dx));
    dy = if_milk(yin,.01*cos(slowtime),0);
    q5 = if_milk(bnot(yin),abs(cos(time)),dx);
    wave_mystery=wave_mystery-1*sin(time*.65*sin(q3));
    wave_mode=random_integer(slowtime%12);
    // per_pixel_1=solipsist = if_milk(equal(q3,0),0,.01*( rad - q3*x + pow(q3,4)*y));
    // per_pixel_2=rot = rot + sin(rad)-5*solipsist-1.5*q5;
    // per_pixel_3=sy = if_milk(equal(q3,0),sy,1-solipsist);
    // per_pixel_4=new_x=rad*.05-x;
    // per_pixel_5=new_y=rad*.05-y;
    // per_pixel_6=zoom=zoom+.01*sin(ang-rad*3.14*sin(if_milk(Above(q2,q1),.5,-.5)*sin(new_X*new_y)))*sin(if_milk(Above(q3,q1),.5,-.5))-.03*sin(Ang*5-rad*sin(if_milk(Above(q3,q2),.5,-.5)));
    warp = 0;
    beatcount = 0;
  }
}
register_preset( Rozzor_and_Idiot__Any_Other_Deep_Rising);
