function Unchained_and_Rovastar__Xen_Traffic() {
  with (Math) {
    fRating=2;
    gamma=1;
    decay=0.975;
    echo_zoom=0.999993;
    echo_alpha=0.5;
    echo_orient=3;
    wave_mode=0;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=0;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1.741913;
    fWaveScale=0.502368;
    fWaveSmoothing=0.36;
    wave_mystery=-0.28;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1;
    fShader=0;
    zoom=0.942044;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0;
    wave_g=0;
    wave_b=0;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.005;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=0.92;
    ib_size=0.004;
    ib_r=0.4;
    ib_g=0.4;
    ib_b=0;
    ib_a=1;
    mv_x=12;
    mv_y=9;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    warp=0;
    old_bass_flop=bass_flop;
    old_treb_flop=treb_flop;
    old_mid_flop=mid_flop;
    chaos=.9+.1*sin(beat);
    entropy=if_milk(bnot(entropy),2,if_milk(equal(pulse,-3.14),1+random_integer(3),entropy));
    bass_thresh = above(bass_att,bass_thresh)*2 + (1-above(bass_att,bass_thresh))*((bass_thresh-1.3)*chaos+1.3);
    bass_flop=abs(bass_flop-equal(bass_thresh,2));
    treb_thresh=above(treb_att,treb_thresh)*2 + (1-above(treb_att,treb_thresh))*((treb_thresh-1.3)*chaos+1.3);
    treb_flop=abs(treb_flop-equal(treb_thresh,2));
    mid_thresh=above(mid_att,mid_thresh)*2 + (1-above(mid_att,mid_thresh))*((mid_thresh-1.3)*chaos+1.3);
    mid_flop=abs(mid_flop-equal(mid_thresh,2));
    bass_changed=bnot(equal(old_bass_flop,bass_flop));
    mid_changed=bnot(equal(old_mid_flop,mid_flop));
    treb_changed=bnot(equal(old_treb_flop,treb_flop));
    bass_residual = bass_changed*sin(pulse*.1*entropy) + bnot(bass_changed)*bass_residual;
    treb_residual = treb_changed*sin(pulse*.1*entropy) + bnot(treb_changed)*treb_residual;
    mid_residual = mid_changed*sin(pulse*.1*entropy) + bnot(mid_changed)*mid_residual;
    pulse=if_milk(above(abs(pulse),3.14),-3.14,pulse+(bass_thresh+mid_thresh+treb_thresh)*.052);
    beat=if_milk(above(abs(beat),3.14),-3.14,beat+(bass+treb+mid)*.01);
    q1=mid_residual;
    q2=bass_residual;
    q3=treb_residual;
    q4=sin(pulse);
    q5=sin(beat);
    mv_r=mv_r+.5*bass_residual;
    mv_g=mv_g+.5*mid_residual;
    mv_b=mv_b+.5*treb_residual;
    mv_a=1.1-(ob_a+ib_a)*chaos*.5;
    mv_x=abs(beat*10)*entropy;
    mv_y=abs(pulse*10)*entropy;
    mv_l=entropy*(q4-q5);
    wave_r=0.8+0.2*bass_flop*mv_g;
    wave_g=0.3+0.3*mid_flop*mv_b;
    wave_b=0.4+0.3*0.1*treb_flop*mv_r;
    ob_r=0.1 + 0.1*sin(time*1.143)+0.2*mv_g;
    ob_g=0.3 + 0.3*sin(time*0.897)+0.3*mv_b;
    ob_b=0.2+0.5*mv_r;
    treb_effect = max(max(treb, treb_att)-1.2,0);
    mid_effect = max(max(mid,mid_att)-1.2,0);
    ib_r = 1 - ob_b;
    ib_g = 1- mv_g;
    ib_b = 0.5*mv_b + 0.5*ob_b;
    ib_a = if_milk(above(treb_effect,0), if_milk(above(mid_effect,0),1,0),0);
    // per_pixel_1=bass_effect = max(max(bass,bass_att)-1.18,0);
    // per_pixel_2=grid=rad*10%(above(q1,q4)+above(q2,q5)+above(q3,q4)) + (sqrt(2)-rad)*10%(above(q1,q5)+above(q2,q4)+above(q3,q5))*q1;
    // per_pixel_3=rot=if_milk(grid,.12*cos(rad*3.14+x*q1*3.14+y*q2*3.14)*(q5+q4),0);
    // per_pixel_4=zoom=zoom-bnot(grid)*atan2(x*q3*3.14,y*q5*3.14)*.14*(x*2-1)+0.12*bass_effect;
    // per_pixel_5=sx=sx+.2*q1*sin(x*1.6)*-grid;
    // per_pixel_6=sy=sy+.2*q2*sin(y*1.6)*(1-grid);
  }
}
register_preset( Unchained_and_Rovastar__Xen_Traffic);
