function Unchained__Beat_Demo_Demonology_Mix() {
  with (Math) {
    fRating=2;
    gamma=1;
    decay=0.996;
    echo_zoom=1;
    echo_alpha=0.5;
    echo_orient=3;
    wave_mode=1;
    wave_additive=1;
    wave_usedots=0;
    bWaveThick=1;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=0;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=1;
    solarize=0;
    invert=0;
    wave_a=0.818;
    fWaveScale=0.374038;
    fWaveSmoothing=0.81;
    wave_mystery=0;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=5.9957;
    warp_scale=1.331;
    zoomexp=1;
    fShader=0;
    zoom=0.968827;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=0.4241;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0;
    ob_r=0.5;
    ob_g=0.5;
    ob_b=0.5;
    ob_a=1;
    ib_size=0;
    ib_r=0.5;
    ib_g=0.5;
    ib_b=0.5;
    ib_a=0;
    mv_x=0;
    mv_y=0;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.85;
    mv_r=0.4999;
    mv_g=0.4999;
    mv_b=0.4999;
    mv_a=1;
    old_bass_flop=bass_flop;
    old_treb_flop=treb_flop;
    old_mid_flop=mid_flop;
    chaos=.5+.5*sin(pulse);
    bass_thresh = above(bass_att,bass_thresh)*2 + (1-above(bass_att,bass_thresh))*((bass_thresh-1.6)*chaos+1.6);
    bass_flop=abs(bass_flop-equal(bass_thresh,2));
    treb_thresh=above(treb_att,treb_thresh)*2 + (1-above(treb_att,treb_thresh))*((treb_thresh-1.6)*chaos+1.6);
    treb_flop=abs(treb_flop-equal(treb_thresh,2));
    mid_thresh=above(mid_att,mid_thresh)*2 + (1-above(mid_att,mid_thresh))*((mid_thresh-1.6)*chaos+1.6);
    mid_flop=abs(mid_flop-equal(mid_thresh,2));
    bass_changed=bnot(equal(old_bass_flop,bass_flop));
    mid_changed=bnot(equal(old_mid_flop,mid_flop));
    treb_changed=bnot(equal(old_treb_flop,treb_flop));
    bass_residual = bass_changed*sin(pulse*3) + bnot(bass_changed)*bass_residual;
    treb_residual = treb_changed*sin(pulse*3) + bnot(treb_changed)*treb_residual;
    mid_residual = mid_changed*sin(pulse*3) + bnot(mid_changed)*mid_residual;
    pulse=if_milk(above(abs(pulse),3.14),-3.14,pulse+(bass_thresh+mid_thresh+treb_thresh)*.005);
    entropy=if_milk(bass_changed*mid_changed*treb_changed,(1+bass_flop+treb_flop+mid_flop)*(1+random_integer(3)),entropy);
    q1=mid_residual;
    q2=bass_residual;
    q3=treb_residual;
    q4=sin(pulse);
    q5=cos(pulse*(.5+.1*entropy));
    q6=sin(pulse*(.5+pow(.25,entropy)));
    q7=above(q1,0)+above(q2,0)+above(q3,0)+above(q3,0)*treb_flop+above(q2,0)*bass_flop+above(q1,0)*mid_flop;
    q8=entropy;
    wave_r=.5+.5*q1;
    wave_b=.5+.5*q2;
    wave_g=.5+.5*q3;
    ob_r=ob_r+ob_r*sin(q1+time*2.18);
    ob_bob_b+ob_b*sin(q2+time*1.73);
    ob_g=ob_g+ob_g*sin(q3+time*2.09);
    ib_r=ib_r+ib_r*cos(q4+q1*2.14);
    ib_b=ib_b+ib_*cos(q4+q2*2.14);
    ib_g=ib_g+ib_g*cos(q4+q3*2.14);
    ob_a=.25+.25*sin(q2+q3*2.14);
    ib_a=.5+.5*sin(q2*2.14+q3);
    ob_size=.025+.025*sin(q3*3+q1);
    ib_size=.025+.025*sin(q1*3+q3);
    warp=0;
    wave_mystery=wave_mystery+.1*sin(time*2.18+q6);
    wave_x=wave_x+.2*sin(time*.811+q1)+.01*(frame%5)*sign(q3);
    wave_y=wave_y+.2*sin(time*2.3+q2)+.01*q7;
    decay=.996+.004*q3;
    // per_pixel_1=snee=bnot(above(sin(ang)-x,.5)*above(q2,0)+above(y-cos(ang),.5)*above(q1,0));
    // per_pixel_2=snur=bnot(below(x,.5)*above(q3,0)+below(y,.5)*below(q7,4));
    // per_pixel_3=grid=sin(sigmoid(sin(y*6.28*q2),sin(x*6.28*q1))*(10+q7));
    // per_pixel_4=rot=snee*if_milk(above(grid,0),snur,bnot(snur));
    // per_pixel_5=zoom=zoom+.05*sin(rad*(q7*2+q5)+q1)*bnot(snee)*if_milk(snur,-1,q3);
    // per_pixel_6=sx=sx+.1*bor(bnot(snee),bnot(snur))*cos(y*3.14*q4);
    // per_pixel_7=sy=sy+.1*bor(bnot(snee),snur)*cos(x*3.14*q6);
  }
}
register_preset( Unchained__Beat_Demo_Demonology_Mix);
