function Unchained__Perverted_Dialect() {
  with (Math) {
    fRating=4;
    gamma=2;
    decay=0.983;
    echo_zoom=1.006596;
    echo_alpha=0;
    echo_orient=3;
    wave_mode=3;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=0;
    darken_center=1;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=0.8;
    fWaveScale=2.047093;
    fWaveSmoothing=0.75;
    wave_mystery=0;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=3.394161;
    fShader=0;
    zoom=1.008148;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.01;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=1;
    ib_size=0.01;
    ib_r=0.25;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0;
    mv_x=12;
    mv_y=9;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    warp = 0;
    wave_r = wave_r + if_milk(above(bass_att,1.4),1,.49*sin(time*2));
    wave_g = wave_g + if_milk(above(bass_att,1.4),0,if_milk(above(treb_att,1.4),1,.49*sin(time*3)));
    wave_b = wave_b + if_milk(above(treb_att,1.4),0,.49*sin(time));
    timer_base=.5;
    q1=sin(time*timer_base*4);
    q2=sin(time*timer_base*2);
    q3=sin(time*timer_base);
    rot=if_milk(above(q1,0),if_milk(above(q2,0),.1,-.1),0);
    zoom=zoom+.05*q2+.05*q1;
    wave_mystery=wave_mystery+.7*q1+.3*q2;
    wave_size=wave_size+0.5*q3;
    cx=cx+.2*q1;
    cy=cy+.2*q3;
    // per_pixel_1=centerx = .5;
    // per_pixel_2=centery = .5;
    // per_pixel_3=crad = abs(rad-.5)*q2;
    // per_pixel_4=grid=abs(x*10-5)%2 + abs(y*10-5)%2;
    // per_pixel_5=sx_temp = if_milk(equal(grid,0),if_milk(above(x,centerx),sx - crad - centerx,sx + crad - centerx),sx);
    // per_pixel_6=sy_temp = if_milk(equal(grid,0),if_milk(above(y,centery),sy - crad - centery,sy + crad - centery),sy);
    // per_pixel_7=sx=if_milk(below(q1,0),sx-sx_temp*q2*.1,sx);
    // per_pixel_8=sy=if_milk(below(q1,0),sy-sx_temp*q2*.1,sy);
  }
}
register_preset( Unchained__Perverted_Dialect);
