function Unchained__Goo_Kung_Fu() {
  with (Math) {
    fRating=2;
    gamma=2;
    decay=0.974;
    echo_zoom=1;
    echo_alpha=0.5;
    echo_orient=0;
    wave_mode=3;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=1;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1;
    fWaveScale=1.074092;
    fWaveSmoothing=0.75;
    wave_mystery=0;
    fModWaveAlphaStart=0.85;
    fModWaveAlphaEnd=1.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1;
    fShader=0;
    zoom=1.01;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.4;
    wave_g=0.4;
    wave_b=0.4;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.005;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=1;
    ib_size=0;
    ib_r=0;
    ib_g=0;
    ib_b=0;
    ib_a=0;
    mv_x=12;
    mv_y=9;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    warp=0;
    wave_r = wave_r + 0.25*(0.6*sin(0.784*time) + 0.4*sin(0.986*time));
    wave_g = wave_g + 0.25*(0.6*sin(0.671*time) + 0.4*sin(1.164*time));
    wave_b = wave_b + 0.25*(0.6*sin(1.423*time) + 0.4*sin(0.687*time));
    zoom=zoom+mid_att*.1;
    // per_pixel_1=timer_a=10*sin(time);
    // per_pixel_2=timer_b=10*sin(time*.5);
    // per_pixel_3=ripple_x=cos(x*timer_a-timer_b)*bass_att;
    // per_pixel_4=ripple_y=cos(y*timer_a-timer_b)*treb_att;
    // per_pixel_5=ripple_r=cos(rad*timer_b-timer_a)*mid_att;
    // per_pixel_6=ripple=ripple_x+ripple_y+ripple_r;
    // per_pixel_7=zoom=zoom+ripple*.1;
  }
}
register_preset( Unchained__Goo_Kung_Fu);
