function Unchained__elite_vectronics() {
  with (Math) {
    fRating=3;
    gamma=1;
    decay=0.978999;
    echo_zoom=2.786752;
    echo_alpha=0.7;
    echo_orient=0;
    wave_mode=0;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=1;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=0.001;
    fWaveScale=1.008144;
    fWaveSmoothing=0;
    wave_mystery=0;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1;
    fShader=0;
    zoom=1.040603;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0;
    wave_g=0;
    wave_b=0;
    wave_x=0.95;
    wave_y=0.5;
    ob_size=0;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=0;
    ib_size=0;
    ib_r=0;
    ib_g=0;
    ib_b=0;
    ib_a=0;
    mv_x=12;
    mv_y=9;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    warp=0;
    dx=-0.0005;
    dy=-0.0005;
    old_bass_flop=bass_flop;
    old_treb_flop=treb_flop;
    old_mid_flop=mid_flop;
    chaos=.9+.1*sin(beat);
    entropy=if_milk(bnot(entropy),2,if_milk(equal(pulse,-3.14),1+random_integer(3),entropy));
    bass_thresh = above(bass_att,bass_thresh)*2 + (1-above(bass_att,bass_thresh))*((bass_thresh-1.3)*chaos+1.3);
    bass_flop=abs(bass_flop-equal(bass_thresh,2));
    treb_thresh=above(treb_att,treb_thresh)*2 + (1-above(treb_att,treb_thresh))*((treb_thresh-1.3)*chaos+1.3);
    treb_flop=abs(treb_flop-equal(treb_thresh,2));
    mid_thresh=above(mid_att,mid_thresh)*2 + (1-above(mid_att,mid_thresh))*((mid_thresh-1.3)*chaos+1.3);
    mid_flop=abs(mid_flop-equal(mid_thresh,2));
    bass_changed=bnot(equal(old_bass_flop,bass_flop));
    mid_changed=bnot(equal(old_mid_flop,mid_flop));
    treb_changed=bnot(equal(old_treb_flop,treb_flop));
    bass_residual = bass_changed*sin(pulse*.1*entropy) + bnot(bass_changed)*bass_residual;
    treb_residual = treb_changed*sin(pulse*.1*entropy) + bnot(treb_changed)*treb_residual;
    mid_residual = mid_changed*sin(pulse*.1*entropy) + bnot(mid_changed)*mid_residual;
    pulse=if_milk(above(abs(pulse),3.14),-3.14,pulse+(bass_thresh+mid_thresh+treb_thresh)*.052);
    beat=if_milk(above(abs(beat),3.14),-3.14,beat+(bass+treb+mid)*.01);
    q1=mid_residual;
    q2=bass_residual;
    q3=treb_residual;
    q4=sin(pulse);
    q5=sin(beat);
    mv_r=mv_r+.5*bass_residual;
    mv_g=mv_g+.5*mid_residual;
    mv_b=mv_b+.5*treb_residual;
    mv_a=1-(ob_a+ib_a)*chaos*.5;
    mv_x=abs(beat*10)*entropy;
    mv_y=abs(pulse*10)*entropy;
    // per_pixel_1=bend = cos(   x*3.14*q2*above(q1,q2) + (rad*3.14*q2-3.14*q3)*above(q2,q3)+(y*3.14*q4)*above(q3,q1));
    // per_pixel_2=zoom = zoom+bend*.05*above(q4+q5,.8);
    // per_pixel_3=something=if_milk(above(q5,0),shif_milkt,q3*0.2*cos((rad+q1)*3.14+q2));
    // per_pixel_4=rot=if_milk(above(zoom-1,.03*q1),if_milk(above(q4,0),rad*.2*q5,something),(x*2-1)*q5);
    // per_pixel_5=grid=x*100%(above(q1,q4)+above(q2,q5)+above(q3,q4)) + y*100%(above(q1,q5)+above(q2,q4)+above(q3,q5));
    // per_pixel_6=zoom=if_milk(grid,zoom-.17*cos(rad*3.14+x*q1*3.14+y*q2*3.14)*(q5+q4),zoom);
    // per_pixel_7=g1=sin(q2*.04*q5);
    // per_pixel_8=g2=sin(q2*.05*q5);
    // per_pixel_9=g3=sin(q2*.06*q5);
    // per_pixel_10=x_shif_milkt=pow(x,2)+x*g1*2+sqr(g1);
    // per_pixel_11=y_shif_milkt=pow(y,2)+y*g2*2+sqr(g2);
    // per_pixel_12=r_shif_milkt=pow(rad,2)+rad*g3*2+sqr(g3);
    // per_pixel_13=zoom=zoom-sin(x_shif_milkt*y_shif_milkt*r_shif_milkt*3.14)*(y*2-1);
    // per_pixel_14=cx=cx+.1*sin(time*.8);
    // per_pixel_15=cy=cy+.1*sin(time*.7);
  }
}
register_preset( Unchained__elite_vectronics);
