function Unchained__Resistance() {
  with (Math) {
    fRating=3;
    gamma=2;
    decay=0.99;
    echo_zoom=1;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=1;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=0;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1;
    fWaveScale=0.671653;
    fWaveSmoothing=0.75;
    wave_mystery=0;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1;
    fShader=1;
    zoom=1;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.95;
    wave_y=0.5;
    ob_size=0.01;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=1;
    ib_size=0;
    ib_r=0;
    ib_g=0;
    ib_b=0;
    ib_a=0;
    mv_x=12;
    mv_y=9;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    warp=0;
    old_bass_flop=bass_flop;
    old_treb_flop=treb_flop;
    old_mid_flop=mid_flop;
    chaos=.9+.1*sin(beat);
    entropy=if_milk(bnot(entropy),2,if_milk(equal(pulse,-3.14),1+random_integer(3),entropy));
    bass_thresh = above(bass_att,bass_thresh)*2 + (1-above(bass_att,bass_thresh))*((bass_thresh-1.3)*chaos+1.3);
    bass_flop=abs(bass_flop-equal(bass_thresh,2));
    treb_thresh=above(treb_att,treb_thresh)*2 + (1-above(treb_att,treb_thresh))*((treb_thresh-1.3)*chaos+1.3);
    treb_flop=abs(treb_flop-equal(treb_thresh,2));
    mid_thresh=above(mid_att,mid_thresh)*2 + (1-above(mid_att,mid_thresh))*((mid_thresh-1.3)*chaos+1.3);
    mid_flop=abs(mid_flop-equal(mid_thresh,2));
    bass_changed=bnot(equal(old_bass_flop,bass_flop));
    mid_changed=bnot(equal(old_mid_flop,mid_flop));
    treb_changed=bnot(equal(old_treb_flop,treb_flop));
    bass_residual = bass_changed*sin(pulse*.1*entropy) + bnot(bass_changed)*bass_residual;
    treb_residual = treb_changed*sin(pulse*.1*entropy) + bnot(treb_changed)*treb_residual;
    mid_residual = mid_changed*sin(pulse*.1*entropy) + bnot(mid_changed)*mid_residual;
    pulse=if_milk(above(abs(pulse),3.14),-3.14,pulse+(bass_thresh+mid_thresh+treb_thresh)*.052);
    beat=if_milk(above(abs(beat),3.14),-3.14,beat+(bass+treb+mid)*.01);
    q1=mid_residual;
    q2=bass_residual;
    q3=treb_residual;
    q4=sin(pulse);
    q5=sin(beat);
    wave_r=wave_r+.5*bass_residual;
    wave_g=wave_g+.5*mid_residual;
    wave_b=wave_b+.5*treb_residual;
    ob_r=if_milk(bass_flop,treb_changed,wave_r);
    ob_b=if_milk(treb_flop,mid_changed,wave_b);
    ob_g=if_milk(mid_flop,bass_changed,wave_g);
    ob_a=.05+.05*cos(wave_r+pulse*.03);
    ob_size=.2+.2*treb_residual;
    ib_r=if_milk(bass_flop,ob_b,ob_g);
    ib_b=if_milk(treb_flop,ob_g,ob_r);
    ib_g=if_milk(mid_flop,ob_r,ob_b);
    ib_size=ob_size*cos(wave_g+pulse*0.4)*.5;
    mv_a=.5+.5*q5;
    mv_x=abs(beat*10)*entropy;
    mv_y=mv_x;
    mv_r=wave_b;
    mv_b=wave_g;
    mv_g=wave_r;
    wave_x = 0.5+sin(2*time)/8;
    wave_y = 0.5-cos(3*time)/6;
    wave_mystery=q5;
    // per_pixel_1=shif_milkt=q3*.1*mid_att;
    // per_pixel_2=checkx=bor(above(abs(q1),x)*below(abs(q2),x),above(abs(q2),x)*below(abs(q1),x));
    // per_pixel_3=checky=bor(above(abs(q1),y)*below(abs(q2),y),above(abs(q2),y)*below(abs(q1),y));
    // per_pixel_4=dx=if_milk(checkx,shif_milkt*q4,dx);
    // per_pixel_5=dy=if_milk(checky,shif_milkt*q5,dy);
    // per_pixel_6=rot=if_milk(checkx*checky,0,shif_milkt);
    // per_pixel_7=zoom=if_milk(above(q5,.8),zoom-shif_milkt*.1,if_milk(below(q5,-.8),zoom+shif_milkt*.1,zoom));
  }
}
register_preset( Unchained__Resistance);
