function Unchained__Bad_Karma_Oddnezz_Style() {
  with (Math) {
    fRating=3;
    gamma=1;
    decay=0.993;
    echo_zoom=0.9999;
    echo_alpha=0.5;
    echo_orient=3;
    wave_mode=0;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=1;
    wave_brighten=0;
    wrap=0;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=0.001;
    fWaveScale=0.01;
    fWaveSmoothing=0.75;
    wave_mystery=-1;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1;
    fShader=0.3;
    zoom=1.486;
    rot=1;
    cx=2;
    cy=-1;
    dx=0;
    dy=0;
    warp=0.01;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0;
    ob_r=1;
    ob_g=0;
    ob_b=0;
    ob_a=0;
    ib_size=0.005;
    ib_r=0;
    ib_g=0;
    ib_b=1;
    ib_a=1;
    mv_x=24.959999;
    mv_y=19.199999;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.85;
    mv_r=0.4999;
    mv_g=0.4999;
    mv_b=0.4999;
    mv_a=0;
    warp=0;
    old_bass_flop=bass_flop;
    old_treb_flop=treb_flop;
    old_mid_flop=mid_flop;
    chaos=.1+.1*sin(pulse);
    bass_thresh =if_milk(above(bass_att,bass_thresh),3,bass_thresh-chaos);
    bass_flop=abs(bass_flop-equal(bass_thresh,3));
    treb_thresh=if_milk(above(treb_att,treb_thresh),3,treb_thresh-chaos);
    treb_flop=abs(treb_flop-equal(treb_thresh,3));
    mid_thresh=if_milk(above(mid_att,mid_thresh),3,mid_thresh-chaos);
    mid_flop=abs(mid_flop-equal(mid_thresh,3));
    bass_changed=bnot(equal(old_bass_flop,bass_flop));
    mid_changed=bnot(equal(old_mid_flop,mid_flop));
    treb_changed=bnot(equal(old_treb_flop,treb_flop));
    bass_residual = bass_changed*sin(pulse*3) + bnot(bass_changed)*bass_residual;
    treb_residual = treb_changed*sin(pulse*3) + bnot(treb_changed)*treb_residual;
    mid_residual = mid_changed*sin(pulse*3) + bnot(mid_changed)*mid_residual;
    pulse=if_milk(above(abs(pulse),3.14),-3.14,pulse+(bass_thresh+mid_thresh+treb_thresh)*.0071);
    entropy=if_milk(equal(pulse,-3.14),bass_flop+mid_flop+treb_flop+random_integer(5),entropy);
    q1=mid_residual;
    q2=bass_residual;
    q3=treb_residual;
    q4=sin(pulse);
    q5=cos(pulse*(.5+.1*entropy));
    q6=sin(pulse*(.5+pow(.25,entropy)));
    q7=above(q1,0)+above(q2,0)+above(q3,0)+above(q3,0)*treb_flop+above(q2,0)*bass_flop+above(q1,0)*mid_flop;
    q8=entropy;
    ib_r=.5+.5*cos(time*1.2+q1*.1);
    ib_b=.5+.5*cos(time*2.811+q2*.1);
    ib_g=.5+.5*cos(time*1.666+q3*.1);
    rot=0;
    // per_pixel_1=grid=pow((sin(ang*10*q1)+x*y*q4)*2,1+q8*q7%11)%2;
    // per_pixel_2=snee=(.3+.2*q6)*q3;
    // per_pixel_3=rot=bnot(grid)*above(x,.5+snee)*above(y,.5-snee) -
    // per_pixel_4=ang*cos(5+(3.14*q6))*below(x,.5+snee)*below(y,.5-snee)*.05;
    // per_pixel_5=sx=sx+sin((q8%4+q7%5)*x*3.14)*bnot(rot)*.004;
    // per_pixel_6=sy=sy+sin((q8%5+q7%4)*y*3.14)*bnot(rot)*.004;
    // per_pixel_7=zoom=zoom+.1*cos(rad*q8*q7);
  }
}
register_preset( Unchained__Bad_Karma_Oddnezz_Style);
