function Unchained__ventilation() {
  with (Math) {
    fRating=3.;
    gamma=2.;
    decay=0.997;
    echo_zoom=0.999999;
    echo_alpha=0.;
    echo_orient=0;
    wave_mode=6;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=0;
    darken_center=0;
    bMotionVectorsOn=0;
    bRedBlueStereo=0;
    mv_x=12;
    mv_y=9;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1.;
    fWaveScale=0.264;
    fWaveSmoothing=0.;
    wave_mystery=0.;
    fModWaveAlphaStart=0.85;
    fModWaveAlphaEnd=1.95;
    warp_speed=1.;
    warp_scale=1.;
    zoomexp=18.423244;
    fShader=0.;
    zoom=1.;
    rot=0.;
    cx=0.5;
    cy=0.5;
    dx=0.;
    dy=0.;
    warp=1.;
    sx=0.990099;
    sy=0.990099;
    wave_r=0.4;
    wave_g=0.4;
    wave_b=0.4;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.005;
    ob_r=0.;
    ob_g=0.;
    ob_b=0.;
    ob_a=1.;
    ib_size=0.;
    ib_r=0.;
    ib_g=0.;
    ib_b=0.;
    ib_a=0.;
    warp=0;
    dx=-0.0005;
    dy=-0.0005;
    wave_random_integerom = random_integer(100)/100;
    wave_r = 1 + sin(-wave_random_integerom*3.1415);
    wave_g = abs(sin(2*wave_random_integerom*3.1415));
    wave_b = sin(wave_random_integerom*3.1415);
    treb_effect = if_milk(above((treb_att*3+mid_att+bass_att)/5,1.4),pow(.99,treb_att),1.03);
    net_effect = if_milk(above(bass_att,0.8*treb_att),1,treb_effect);
    zoom = net_effect;
    rot = rot + rot_residual;
    bass_thresh = 1.3;
    bass_thresh = above((bass_att*3+mid_att+treb_att)/5,bass_thresh)*2 + (1-above(bass_att,bass_thresh))*((bass_thresh-1.3)*0.96+1.3);
    shif_milkt = (tan(time*7)) -0.05;
    shif_milkt = if_milk(above(shif_milkt,0),0,if_milk(below(shif_milkt,-0.1),-0.1,shif_milkt));
    rot_residual = if_milk(equal(bass_thresh,2),shif_milkt,rot_residual);
    timer=sin(time*.888);
    wave_mystery=if_milk(above(timer,0),0,1);
    q1=timer;
    // per_pixel_1=disk_shif_milkt = if_milk(equal(abs(sin(ang)), if_milk(above(q1,0),0,1)), -rot, 0.05);
    // per_pixel_2=timer=sin(time*1.3);
    // per_pixel_3=x_or_y=if_milk(above(q1,0),y,x);
    // per_pixel_4=rot = rot + if_milk(equal(x_or_y*10%2,0),if_milk(below(timer,0),disk_shif_milkt,-rot),if_milk(above(timer,0),disk_shif_milkt,-rot));
  }
}
register_preset( Unchained__ventilation);
