function Zylot_and_Krash__Extremophile() {
  with (Math) {
    fRating=2;
    gamma=1.7;
    decay=0.997;
    echo_zoom=1.000224;
    echo_alpha=0.5;
    echo_orient=1;
    wave_mode=6;
    wave_additive=1;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=0;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=1;
    solarize=1;
    invert=0;
    wave_a=1.0031;
    fWaveScale=1.004873;
    fWaveSmoothing=0;
    wave_mystery=0;
    fModWaveAlphaStart=1.01;
    fModWaveAlphaEnd=1.01;
    warp_speed=0.999994;
    warp_scale=1.002083;
    zoomexp=0.627608;
    fShader=1;
    zoom=0.9948;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0.01;
    dy=0.01;
    warp=0.01;
    sx=1;
    sy=1;
    wave_r=0;
    wave_g=0;
    wave_b=0;
    wave_x=0;
    wave_y=0.5;
    ob_size=0.005;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=0.0299;
    ib_size=0;
    ib_r=0.25;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0;
    mv_x=0;
    mv_y=0;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.85;
    mv_r=0.4999;
    mv_g=0.4999;
    mv_b=0.4999;
    mv_a=0;
    volume = 0.3*(bass+mid+att);
    beatrate = equal(beatrate,0) + (1-equal(beatrate,0))*(below(volume,0.01) + (1-below(volume,0.01))*beatrate);
    lastbeat = lastbeat + equal(lastbeat,0)*time;
    meanbass_att = 0.1*(meanbass_att*9 + bass_att);
    peakbass_att = max(bass_att,peakbass_att);
    beat = above(volume,0.8)*below(peakbass_att - bass_att, 0.05*peakbass_att)*above(time - lastbeat, 0.1 + 0.5*(beatrate - 0.1));
    beatrate = max(if_milk(beat,if_milk(below(time-lastbeat,2*beatrate),0.1*(beatrate*9 + time - lastbeat),beatrate),beatrate),0.1);
    peakbass_att = beat*bass_att + (1-beat)*peakbass_att*(above(time - lastbeat, 2*beatrate)*0.95 + (1-above(time - lastbeat, 2*beatrate))*0.995);
    lastbeat = beat*time + (1-beat)*lastbeat;
    peakbass_att = max(peakbass_att,1.1*meanbass_att);
    xamptarg = if_milk(equal(frame%15,0),min(0.25*volume*bass_att,0.5),xamptarg);
    xamp = xamp + 0.5*(xamptarg-xamp);
    xdir = if_milk(above(abs(xpos),xamp),-sign(xpos),if_milk(below(abs(xspeed),0.1),2*above(xpos,0)-1,xdir));
    xspeed = xspeed + xdir*xamp - xpos - xspeed*0.055*below(abs(xpos),xamp);
    xpos = xpos + 0.001*xspeed;
    wave_x = 1.5*xpos + 0.5;
    yamptarg = if_milk(equal(frame%15,0),min(0.15*volume*treb_att,0.5),yamptarg);
    yamp = yamp + 0.5*(yamptarg-yamp);
    ydir = if_milk(above(abs(ypos),yamp),-sign(ypos),if_milk(below(abs(yspeed),0.1),2*above(ypos,0)-1,ydir));
    yspeed = yspeed + ydir*yamp - ypos - yspeed*0.055*below(abs(ypos),yamp);
    ypos = ypos + 0.001*yspeed;
    mode = if_milk(beat,random_integer(2),mode);
    q1 = (25+15*sin(time*1.56) + 10*sin(time*0.643))*0.08;
    q2 = 1 - mode*2;
    red=if_milk(below(frame%6,3),bass*0.5,0);
    blue=if_milk(above(frame%6,2),bass*0.5,0);
    green=0.9+sin(time)*0.1;
    q3 = 3 + sin(time*0.496) + sin(time*0.591);
    mode2 = frame%2;
    wave_r = if_milk(mode2,red,green);
    wave_g = if_milk(mode2,green,0.5*blue);
    wave_b = if_milk(mode2,blue,red);
    wave_mode = if_milk(mode2,6,0);
    wave_x = if_milk(mode2,0,0.5 + xpos + 0.1*sin(time));
    wave_y = if_milk(mode2,0.5,0.5+ ypos + 0.1*cos(time));
    q4 = 0.5 + xpos + 0.18*sin(time);
    q5 = 0.5 - ypos - 0.18*cos(time);
    wave_mystery = if_milk(mode2,0,-0.4);
    wave_r=abs(wave_r-my_random_integer);
    wave_b=abs(wave_b-my_random_integer);
    wave_g=abs(wave_g-my_random_integer);
    // per_pixel_1=dx = dx*pow(-1,0&(13+q1 - 2*(q2*y)))*min(0.5*bass,1.2);
    // per_pixel_2=dy = dy*pow(-1,0&(13+q1 - 5*(x*q3)))*min(0.5*bass,1.2)-0.01;
    // per_pixel_3=newx = x - q4;
    // per_pixel_4=newy = y - q5;
    // per_pixel_5=newrad = min(sqrt((newx)*(newx)+0.5625*(newy)*(newy))*2,1);
    // per_pixel_6=newzoom = pow(1.03, pow(0.01+sin(newrad*newrad), newrad*2-1));
    // per_pixel_7=dx = (min(5*newrad,1)*dx + max(1 - newrad*5,0)*((newx)*newzoom - newx*bass));
    // per_pixel_8=dy = (min(5*newrad,1)*dy + max(1 - newrad*5,0)*((newy)*newzoom - newy*treb));
    // per_pixel_9=sy=sy+above(x,.5)*sin(rad*q5*1.68*mid)*.8;
    // per_pixel_10=zoom=zoom-.04*sin((x-.5)*8+q4)*sin(y*31.4+q3*sin(bass+ang*treb+time));
    my_random_integer=abs(sin(random_integer(500)));
  }
}
register_preset( Zylot_and_Krash__Extremophile);
