function Zylot_and_Mstress__Toxic_Storm_On_Acid_Sea_The_End_Of_The_World_reMix() {
  with (Math) {
    fRating=3;
    gamma=1.998;
    decay=0.99;
    echo_zoom=2;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=6;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=1;
    wave_brighten=0;
    wrap=1;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=1;
    solarize=0;
    invert=0;
    wave_a=0.0513;
    fWaveScale=2.778365;
    fWaveSmoothing=0.9;
    wave_mystery=-0.799999;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=2.853;
    zoomexp=1;
    fShader=0;
    zoom=1.001829;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=0.01;
    sx=1;
    sy=1;
    wave_r=0.77;
    wave_g=0.6;
    wave_b=0.6;
    wave_x=0.42;
    wave_y=0.5;
    ob_size=0.0055;
    ob_r=0;
    ob_g=0;
    ob_b=0.52;
    ob_a=0.18;
    ib_size=0.0005;
    ib_r=0.291;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0;
    mv_x=64;
    mv_y=2.4;
    mv_dx=0;
    mv_dy=-0.1;
    mv_l=5;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    wave_r = min(1,max(0,0.2*bass));
    wave_g = min(1,max(0,0.2*mid));
    wave_b = min(1,max(0,0.2*treb));
    xpos = 0.01*random_integer(100);
    wave_x =  xpos;
    decay = .99;
    
    //Thanks to Zylot for rainbow generator
    counter1 = if_milk(equal(counter2,1),if_milk(equal(counter1,1),0,counter1+.2),1);
    counter2 = if_milk(equal(counter1,1),if_milk(equal(counter2,1),0,counter2+.2),1);
    cdelay1 = if_milk(equal(cdelay2,1),1,if_milk(equal(colorcounter%2,1),if_milk(equal(counter1,1),2 ,0), if_milk(equal(counter2,1),2,0)));
    cdelay2 = if_milk(equal(cdelay1,2),1,0);
    colorcounter = if_milk(above(colorcounter,7),0,if_milk(equal(cdelay1,1),colorcounter+1,colorcounter));
    ob_r = .5*if_milk(equal(colorcounter,1),1, if_milk(equal(colorcounter,2),1, if_milk(equal(colorcounter,3),1, if_milk(equal(colorcounter,4),sin(counter2+2.1), if_milk(equal(colorcounter,5),0, if_milk(equal(colorcounter,6),0,sin(counter1)))))));
    ob_g = .5*if_milk(equal(colorcounter,1),0, if_milk(equal(colorcounter,2),sin(counter2*.5), if_milk(equal(colorcounter,3),sin((counter1+1.75)*.4), if_milk(equal(colorcounter,4),1, if_milk(equal(colorcounter,5),1, if_milk(equal(colorcounter,6),sin(counter2+2),0))))));
    ob_b = if_milk(equal(colorcounter,1),sin(counter1+2.1), if_milk(equal(colorcounter,2),0, if_milk(equal(colorcounter,3),0, if_milk(equal(colorcounter,4),0, if_milk(equal(colorcounter,5),sin(counter1), if_milk(equal(colorcounter,6),1,1))))));
    
    q3=10+bass+mid+treb;
    // per_pixel_1=empty = 1-(above(x,.97)*below(y,.46));
    // per_pixel_2=sea=q3;
    // per_pixel_3=mang=atan((-0.5+0.1*sin(time)+y)/(-1+x*3))-.65+.20*sin(time);
    // per_pixel_4=cx = floor(x*sea)/sea;
    // per_pixel_5=cy = floor(y*sea)/sea;
    // per_pixel_6=rot = rot+.2*(bass_att)*empty-.3*(1-2*below(2*sin(mang)+2*cos(mang),.2*bass))*empty;
    // per_pixel_7=dy = dy +sin(time*.3)*.01*cos(rad/x);
  }
}
register_preset( Zylot_and_Mstress__Toxic_Storm_On_Acid_Sea_The_End_Of_The_World_reMix);
