function Zylot__Present_for_Saddam() {
  with (Math) {
    fRating=1;
    gamma=1.7;
    decay=0.98;
    echo_zoom=2;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=0;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=0;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1.078276;
    fWaveScale=0.274297;
    fWaveSmoothing=0.75;
    wave_mystery=-0.48;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1;
    fShader=0;
    zoom=1;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.005;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=1;
    ib_size=0.01;
    ib_r=0.25;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0;
    mv_x=64;
    mv_y=48;
    mv_dx=0;
    mv_dy=0;
    mv_l=0;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    warp = 0;
    wave_x = locx;
    wave_y = if_milk(below(locy,.01),.01,locy);
    wave_r = if_milk(equal(expt2,0),.6,1);
    wave_g = .6;
    wave_b = if_milk(equal(expt2,0),.6,.05);
    wave_mode = if_milk(equal(expt2,0),2,0);
    locx=locx-xspeed;
    locy=if_milk(below(locy,.02),.01,locy-yspeed);
    xspeed = if_milk(below(locy,.01),0,xspeed - (xspeed)*.03);
    yspeed = if_milk(below(locy,.01),0,yspeed+(yspeed)*.03);
    decay = if_milk(below(locy,.02),.94,.4);
    expt = if_milk(below(locy,.011),if_milk(below(expt,0.001),0,expt-.01),expt);
    expt2 = if_milk(equal(expt,0),if_milk(below(expt2,0.001),0,expt2-.01),expt2);
    q1 = locx;
    q2 = locy;
    q3 = expt;
    q4 = expt2;
    monitor = timer;
    timer = if_milk(above(timer,.01),timer-.01,6);
    yspeed = if_milk(below(timer,.012),.02,yspeed);
    xspeed = if_milk(below(timer,.012),random_integer(200)*.0001,xspeed);
    locy = if_milk(below(timer,.012),1,locy);
    locx = if_milk(below(timer,.012),(random_integer(80)+20)*.01,locx);
    expt = if_milk(below(timer,.012),.5,expt);
    expt2 = if_milk(below(timer,.012),1,expt2);
    // per_pixel_1=random_integeromn = random_integer(100)*.006;
    // per_pixel_2=xcenter = q1;
    // per_pixel_3=ycenter = abs(q2-1);
    // per_pixel_4=dx = if_milk(below(q2,.011),if_milk(equal(q3,0),if_milk(equal(q4,0),dx + (x - xcenter)*.03,dx + (x - xcenter)*.1),dx + (x - xcenter)*random_integeromn),0);
    // per_pixel_5=dy = if_milk(below(q2,.011),if_milk(equal(q3,0),if_milk(equal(q4,0),dy + (y - ycenter)*.06*bass,dy + (y - ycenter)*.1),dy + (y - ycenter)*random_integeromn),0);
    yspeed = .02;
    xspeed = random_integer(200)*.0001;
    locy = 1;
    locx = (random_integer(80)+20)*.01;
    expt = .5;
    expt2 = 1;
    timer = 6;
  }
}
register_preset( Zylot__Present_for_Saddam);
