function Zylot__light_of_the_path() {
  with (Math) {
    fRating=5;
    gamma=2.;
    decay=0.98;
    echo_zoom=2.;
    echo_alpha=0.;
    echo_orient=0;
    wave_mode=3;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=1;
    darken_center=0;
    bMotionVectorsOn=0;
    bRedBlueStereo=0;
    mv_x=12;
    mv_y=9;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=0.8;
    fWaveScale=1.;
    fWaveSmoothing=0.75;
    wave_mystery=-0.44;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1.;
    warp_scale=1.;
    zoomexp=1.;
    fShader=0.;
    zoom=1.;
    rot=0.;
    cx=0.5;
    cy=0.5;
    dx=0.;
    dy=0.;
    warp=1.;
    sx=1.;
    sy=1.;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.07;
    wave_y=0.5;
    ob_size=0.01;
    ob_r=0.;
    ob_g=0.;
    ob_b=0.;
    ob_a=0.;
    ib_size=0.01;
    ib_r=0.25;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0.;
    dx = dx - .001;
    dy = dy - .001;
    warp = 0;
    wave_r = wave_r + .2*sin(time*1.33)+bass*.3;
    wave_g = wave_g + .2*sin(time)+treb*.3;
    wave_b = wave_b + .2*sin(time*.988)+mid*.3;
    // per_pixel_1=zoomlv = .1*sin(ang*1000+time)+.05;
    // per_pixel_2=zoom = zoom + zoomlv;
    // per_pixel_3=dx = zoomlv;
  }
}
register_preset( Zylot__light_of_the_path);
