function Zylot__Block_Of_Sound_Fractal_Construction_Mix() {
  with (Math) {
    fRating=3;
    gamma=2;
    decay=0.98;
    echo_zoom=2;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=2;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=1;
    bModWaveAlphaByVolume=0;
    wave_brighten=0;
    wrap=1;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=3.558724;
    fWaveScale=0.124746;
    fWaveSmoothing=0;
    wave_mystery=-0.5;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1;
    fShader=0;
    zoom=1;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.03;
    wave_y=0.96;
    ob_size=0.01;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=0;
    ib_size=0.01;
    ib_r=0.25;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0;
    mv_x=12;
    mv_y=9;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    warp = 0;
    vol = 0.167*(bass+mid+att);
    xamptarg = if_milk(equal(frame%15,0),min(0.5*vol*bass_att,0.5),xamptarg);
    xamp = xamp + 0.5*(xamptarg-xamp);
    xdir = if_milk(above(abs(xpos),xamp),-sign(xpos),if_milk(below(abs(xspeed),0.1),2*above(xpos,0)-1,xdir));
    xspeed = xspeed + xdir*xamp - xpos - xspeed*0.055*below(abs(xpos),xamp);
    xpos = xpos + 0.001*xspeed;
    yamptarg = if_milk(equal(frame%15,0),min(0.3*vol*treb_att,0.5),yamptarg);
    yamp = yamp + 0.5*(yamptarg-yamp);
    ydir = if_milk(above(abs(ypos),yamp),-sign(ypos),if_milk(below(abs(yspeed),0.1),2*above(ypos,0)-1,ydir));
    yspeed = yspeed + ydir*yamp - ypos - yspeed*0.055*below(abs(ypos),yamp);
    ypos = ypos + 0.001*yspeed;
    wave_x = centerx;
    wave_y = abs(centery-1);
    centerx = 1.75*xpos + 0.5;
    centery = 1.75*ypos + 0.5;
    q1 = centerx;
    q2 = centery;
    q3 = .06 + bass*.04;
    wave_r =  bass*.3;
    wave_g =  treb*.3;
    wave_b =  mid*.3;
    // per_pixel_1=zoom = if_milk(above(x,q1 - q3),if_milk(below(x,q1 + q3),if_milk(above(y,q2 - q3),if_milk(below(y,q2 + q3),1,.94+ze),.94+ze),.94+ze),.94+ze);
    // per_pixel_2=zoomerx = if_milk(above(x,q1),.01,-.01);
    // per_pixel_3=zoomery = if_milk(above(y,q2),.01,-.01);
    // per_pixel_4=dx = if_milk(above(x,q1 - q3),if_milk(below(x,q1 + q3),if_milk(above(y,q2 - q3),if_milk(below(y,q2 + q3),zoomerx,.7+dxe),.7+dxe),.7+dxe),.7+dxe);
    // per_pixel_5=dy = if_milk(above(x,q1 - q3),if_milk(below(x,q1 + q3),if_milk(above(y,q2 - q3),if_milk(below(y,q2 + q3),zoomery,.7+dye),.7+dye),.7+dye),.7+dye);
    // per_pixel_6=dxe = .2 + .2*sin(time*.444);
    // per_pixel_7=dye = .2+.2*cos(time*.222);
    // per_pixel_8=ze = .04*sin(time*.777);
  }
}
register_preset( Zylot__Block_Of_Sound_Fractal_Construction_Mix);
