function Zylot__The_Deeper() {
  with (Math) {
    gamma=2.;
    decay=0.98;
    echo_zoom=2.;
    echo_alpha=0.;
    echo_orient=0;
    wave_mode=6;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=1;
    darken_center=0;
    bMotionVectorsOn=0;
    bRedBlueStereo=0;
    mv_x=12;
    mv_y=9;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=0.8;
    fWaveScale=0.302995;
    fWaveSmoothing=0.75;
    wave_mystery=1.;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1.;
    warp_scale=1.;
    zoomexp=1.;
    fShader=0.;
    zoom=1.;
    rot=0.;
    cx=0.5;
    cy=0.5;
    dx=0.;
    dy=0.;
    warp=1.;
    sx=1.;
    sy=1.;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.4999;
    wave_x=0.98;
    wave_y=0.5;
    warp = 0;
    sy = .9;
    sx = 1.02;
    wave_r = wave_r + .25*sin(time*.444);
    wave_g = wave_g + .25*sin(time*.333);
    wave_b = wave_b + .25*sin(time*.222);
    wave_r = wave_r + bass*.3;
    wave_g = wave_g + treb*.3;
    wave_b = wave_b + mid*.3;
    // per_pixel_1=sy = .9;
    // per_pixel_2=zoom = zoom - rad*.1;
    // per_pixel_3=rot = rot + .6 + .39*sin((rot + rad*.2)+time);
    ;
    fRating=2;
  }
}
register_preset( Zylot__The_Deeper);
