function Zylot__Mixing_Pot() {
  with (Math) {
    gamma=2.;
    decay=0.98;
    echo_zoom=2.;
    echo_alpha=0.;
    echo_orient=0;
    wave_mode=2;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=0;
    darken_center=0;
    bMotionVectorsOn=0;
    bRedBlueStereo=0;
    mv_x=12;
    mv_y=9;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=0.8;
    fWaveScale=1.;
    fWaveSmoothing=0.72;
    wave_mystery=0.;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1.;
    warp_scale=1.;
    zoomexp=1.;
    fShader=0.;
    zoom=0.999963;
    rot=0.;
    cx=0.5;
    cy=0.5;
    dx=0.;
    dy=0.;
    warp=1.;
    sx=1.;
    sy=0.999831;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.5;
    warp = 0;
    wave_r = wave_r + .255*sin(time*.366);
    wave_g = wave_g + .255*sin(time*.222);
    wave_b = wave_b + .255*sin(time*.288);
    wave_r = wave_r + bass*.3;
    wave_g = wave_g + treb*.3;
    wave_b = wave_b + mid*.3;
    zoom = zoom + .01 + .1*sin(time);
    zoom = zoom - bass*.1;
    cx = cx + .1*sin(time*.111);
    cy = cy + .1*sin(time*.222);
    // per_pixel_1=zoom = zoom + abs(x-.5);
    // per_pixel_2=zoom = zoom + abs(x-.5);
    // per_pixel_3=rot = .2*sin(rad*(2 - 10*sin(time))-time*4);
    fRating=3;
  }
}
register_preset( Zylot__Mixing_Pot);
