function Zylot__Rainbow_Planet_Under_Attack() {
  with (Math) {
    fRating=2;
    gamma=2;
    decay=0.98;
    echo_zoom=2;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=2;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=0;
    darken_center=1;
    bRedBlueStereo=0;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=0.8;
    fWaveScale=0.692005;
    fWaveSmoothing=0.75;
    wave_mystery=-0.64;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1;
    fShader=0;
    zoom=1;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.49;
    ob_size=0.005;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=1;
    ib_size=0.01;
    ib_r=0.25;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0;
    mv_x=12;
    mv_y=9;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    warp = 0;
    wave_r = wave_r + .25*sin(time*.555);
    wave_g = if_milk(above(frame%2,0),wave_b + .25*cos(time*.888),0);
    wave_b = if_milk(above(frame%2,0),wave_b + .25*sin(time),0);
    wave_mode = 2*above(frame%2,0);
    wave_x = if_milk(above(frame%2,0),wave_x,random_integer(100)*.01);
    wave_y = if_milk(above(frame%2,0),wave_y,(random_integer(30)+70)*.01);
    // per_pixel_1=zoom = bass_att*.2 + (3*y)+2*(pow(x,2))*.01;
    // per_pixel_2=zoom = if_milk(below(zoom,1),.995,zoom);
    // per_pixel_3=dx = if_milk(below(zoom,1),(random_integer(100)-50)*.0003,0);
    // per_pixel_4=dy = if_milk(below(zoom,1),(random_integer(100)-50)*.0003,0);
  }
}
register_preset( Zylot__Rainbow_Planet_Under_Attack);
