function Zylot__Tunnel_Of_Illusion() {
  with (Math) {
    fRating=3;
    gamma=2;
    decay=0.98;
    echo_zoom=0.333566;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=0;
    wave_additive=0;
    wave_usedots=0;
    bWaveThick=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=1;
    darken_center=0;
    bRedBlueStereo=0;
    brighten=1;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=0.532001;
    fWaveScale=0.01;
    fWaveSmoothing=0;
    wave_mystery=-0.3999;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1;
    warp_scale=1;
    zoomexp=1;
    fShader=0;
    zoom=1;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=1;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.01;
    ob_r=0;
    ob_g=0;
    ob_b=0;
    ob_a=0;
    ib_size=0.01;
    ib_r=0.25;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0;
    mv_x=12;
    mv_y=9;
    mv_dx=0;
    mv_dy=0;
    mv_l=0.9;
    mv_r=1;
    mv_g=1;
    mv_b=1;
    mv_a=0;
    warp = 0;
    wave_r = bass*.5;
    wave_g = treb*.5;
    wave_b = mid*.5;
    decay = .99;
    // per_pixel_1=zoom = 1.03+rad*.1;
    // per_pixel_2=zoomexp =1 - 1*sin(rad*time*10);
  }
}
register_preset( Zylot__Tunnel_Of_Illusion);
