function Zylot__Digiscape_Advanced_Processor() {
  with (Math) {
    gamma=2;
    decay=0.900001;
    echo_zoom=2;
    echo_alpha=0;
    echo_orient=0;
    wave_mode=6;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=0;
    darken_center=0;
    bMotionVectorsOn=0;
    bRedBlueStereo=0;
    mv_x=12;
    mv_y=9;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=5.053452;
    fWaveScale=2.448587;
    fWaveSmoothing=0.9;
    wave_mystery=0;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=0.01;
    warp_scale=0.01;
    zoomexp=1;
    fShader=0;
    zoom=1;
    rot=0;
    cx=0.5;
    cy=0.5;
    dx=0;
    dy=0;
    warp=0.01;
    sx=1;
    sy=1;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.4999;
    wave_y=0.4999;
    wave_r = wave_r + .3*sin(time*.222);
    wave_g = wave_g + .3*sin(time*.123);
    wave_b = wave_b + .3*sin(time*.444);
    decay = .9 + .1*sin(time*.01);
    // per_pixel_1=dx = dx - .08*tan(time + (x)*47);
    // per_pixel_2=dy = .01*sin((-time*.22 + (y+.5)));
    fRating=2;
  }
}
register_preset( Zylot__Digiscape_Advanced_Processor);
