function Zylot__Ether_Storm() {
  with (Math) {
    fRating=5.;
    gamma=2.;
    decay=0.97;
    echo_zoom=2.;
    echo_alpha=0.;
    echo_orient=0;
    wave_mode=2;
    wave_additive=0;
    wave_usedots=0;
    bModWaveAlphaByVolume=0;
    wave_brighten=1;
    wrap=0;
    darken_center=0;
    bMotionVectorsOn=0;
    bRedBlueStereo=0;
    mv_x=12;
    mv_y=9;
    brighten=0;
    darken=0;
    solarize=0;
    invert=0;
    wave_a=1.958904;
    fWaveScale=0.550447;
    fWaveSmoothing=0.36;
    wave_mystery=-0.5;
    fModWaveAlphaStart=0.75;
    fModWaveAlphaEnd=0.95;
    warp_speed=1.;
    warp_scale=1.;
    zoomexp=1.;
    fShader=0.;
    zoom=1.;
    rot=0.;
    cx=0.5;
    cy=0.5;
    dx=0.;
    dy=0.;
    warp=1.;
    sx=1.;
    sy=1.;
    wave_r=0.5;
    wave_g=0.5;
    wave_b=0.5;
    wave_x=0.5;
    wave_y=0.5;
    ob_size=0.31;
    ob_r=0.3;
    ob_g=0.;
    ob_b=0.;
    ob_a=0.;
    ib_size=0.01;
    ib_r=0.25;
    ib_g=0.25;
    ib_b=0.25;
    ib_a=0.;
    dx = dx - .001;
    dy = dy - .001;
    wave_r = wave_r + .5*sin(time*.666);
    wave_g = wave_g + .5*sin(time*.777);
    wave_b = wave_b + .5*sin(time*.888);
    // per_pixel_1=dx = if_milk(above(y,.7),001.*asin((x-.5)*(y-.7)),dx);
    // per_pixel_2=dx = if_milk(below(y,.3),001.*-asin((x-.5)*(y-.3)),dx);
    // per_pixel_3=dy = (y-.5)*.05;
    // per_pixel_4=warp = dx*50;
  }
}
register_preset( Zylot__Ether_Storm);
